class ActionTypes {
  static const LIST_USERS_REQUEST = 'LIST_USERS_REQUEST';
  static const LIST_USERS_SUCCESS = 'LIST_USERS_SUCCESS';
  static const LIST_USERS_FAILURE = 'LIST_USERS_FAILURE';

  static const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST';
  static const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
  static const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE';
}
